### ISSUE TITLE
Buttons are not visible after update to version 1.0.3

### ISSUE THREAD

**Issue by mauricebish** [tungmeister/hass-blind-card#12]
Buttons are not visible after update to V 1.0.3
Did a rollback to V 1.0.2 and the buttons are visible again.

Steps to reproduce
1. update to version 1.0.3 -> reload, restart HA, clean cache -> buttons not visible
2. rollback to 1.0.2 -> reload, restart HA, clean cache -> buttons visible
3. update to version 1.0.3 again -> reload, restart HA -> clean cache, buttons not visible
4. rollback to 1.0.2 -> reload, restart HA, clean cache -> buttons visible

Home assistant version: core-2021.10.6

**Comment by Nicholaiii** [comment]
Release notes for 1.0.3 explicitly say it's changed for 2021.11 icon changes. Update your HA and it should work.
